events {}

http {
    server {
        listen 80;
        server_name pretalx.congresso-spmc.com;

        add_header Referrer-Policy "no-referrer";
        add_header X-Content-Type-Options "nosniff";
        add_header X-Frame-Options "DENY";
        add_header X-XSS-Protection "1; mode=block";

        # Serve /media files with no directory listings and as attachments
        location /media/ {
            alias /data/media/;
            access_log off;
            autoindex off;
            add_header Content-Disposition "attachment";
            add_header Cache-Control "public, max-age=2592000, immutable";
        }

        # Serve /static files
        location /static/ {
            alias /data/static/;
            access_log off;
            autoindex off;
            add_header Cache-Control "public, max-age=2592000, immutable";
        }

        location / {
            proxy_pass http://pretalx:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
